### PR TITLE
More Intllib support / German translations

### PR DESCRIPTION
**Pull request by zeuner**
On this branch, I'm adding german translations for various texts in the game, and also more intllib support for different game mods in order to allow more texts to be translated.

So, this should also provide the basis for translating to more languages.

### CODE REVIEW

**Comment by neinwhal** [comment]
Closing this due to lack of activity, anyone is welcome to adopt or clean this up for merge.

**Comment by zeuner** [comment]
Would you like to specify what kind of cleanup you were looking for?

It worked for me, and the main reason for inactivity was that we didn't encounter more untranslated text while playing. So chances are that the commits could help other users who look for a translated experience.

**Comment by neinwhal** [comment]
Several parts of the translations are outdated, and minetest has a builtin translation manager now: `minetest.get_translator`

Also, I don't think there was any mention that this was completed? So there was never an indicator as to when this was ready for merge, that would be helpful.

If the issues as mentioned are fixed, I'm open for an merge.

**Comment by zeuner** [comment]
Regarding `intllib`, I was sticking to the translation manager already being used by LOTT (e.g. https://github.com/minetest-LOTR/Lord-of-the-Test/blob/master/mods/lottachievements/intllib.lua). I agree that Minetest's builtin translation API is stable nowadays, and I'm open to update the code. This will also allow translations based on the client language. This will take some time, though, as there are some differences between `intllib` and `minetest.get_translator`.

I merged `master` and cleaned up the conflicts. Will move on from there.

Regarding completing, it's a big game and I'm doing this in spare time, but I was thinking that internationalization support is a feature that makes sense to merge early and eagerly because that would prevent the translation API calls being lost when code is moved between files, and it would enable contributors to easily add more translations where API calls are already present.

It seems that now that the PR is closed, github won't update the commits I'm pushing. Can we fix this somehow or should I rather open a new PR?

**Comment by neinwhal** [comment]
Do open a new PR. When I said "complete", I mean I need a confirmation from your side as to whether the pull request is ready to merge with whatever translation changes you have provided, incomplete translation is, of course, acceptable, and I'm happy for any amount of translation contributions.

**Comment by zeuner** [comment]
Will do (intllib support soon won't be accurate anyway).

I only pushed to the branch when the code could be started, so I guess merging would always work.

Maybe a good time to merge will be after fully removing the `intllib` dependency.

**Pull request closed without merging**
