### PR TITLE
Add lore scroll to Mirkwood Elf chest.

### PR DESCRIPTION
**Pull request by NewbProgrammer101**

### CODE REVIEW

**Comment by NewbProgrammer101** [comment]
Added second lore scroll to Gondor chest.

**Comment by Amaz1** [comment]
As these poems are copyrighted, this can't be merged, sorry.

**Comment by NewbProgrammer101** [comment]
Okay...
Didn't pay attention to Creative Commons copyrights because I got so used to GPL being everywhere. 

I'll write my own poems, if they're not as good as Tolkien's writing then that's too bad because that'll be as far as I can go in writing.

**Comment by Anth0rx** [comment]
> Didn't pay attention to Creative Commons copyrights because I got so used to GPL being everywhere.
Are the poems you added licensed under a Creative Commons license? Which one is is?

**Comment by NewbProgrammer101** [comment]
All of the poems can be redistributed under (CC BY-SA 3.0)

**Comment by Anth0rx** [comment]
Ah okay, so why does this pose a problem for LOTT, then? CC-BY-SA-3.0 by itself is not GPL-compatible, but as of my understanding it is possible to relicense CC-BY-SA-3.0 works under CC-BY-SA-4.0, which is in turn GPL-compatible. Another question is: Why is the LGPL preferred over the GPL?

**Comment by Amaz1** [comment]
> All of the poems can be redistributed under (CC BY-SA 3.0)

Do you have a source for this? As all of these poems come straight from the works of J.R.R. Tolkein, I wouldn't think that they are, and that they're all rights reserved.

> Ah okay, so why does this pose a problem for LOTT, then? CC-BY-SA-3.0 by itself is not GPL-compatible, but as of my understanding it is possible to relicense CC-BY-SA-3.0 works under CC-BY-SA-4.0, which is in turn GPL-compatible. Another question is: Why is the LGPL preferred over the GPL?

If they were CC BY-SA, that would be okay, but as I said, I'm very doubtful that they are... The LGPL is preferred mainly because that's what Minetest & Minetest Game use, and a larger percentage of mods are under the LGPL than the GPL. Of course, it's possible to relicense LGPL stuff as GPL, but I really don't like it when that's done, because it means that the original mod can't use any changes made "upstream." Personally, I'd prefer MIT or BSD, but, that's a whole different issue :P (And isn't going to happen, due to Minetest Game being LGPL.)

**Comment by Anth0rx** [comment]
> Do you have a source for this?

That would be interesting indeed.

> because it means that the original mod can't use any changes made "upstream."

Why is that? Which original mod?

**Comment by Amaz1** [comment]
> > because it means that the original mod can't use any changes made "upstream."

> Why is that? Which original mod?

LGPL can be relicensed as GPL, but GPL can't be relicensed as LGPL. Therefore, if there was a change made to lottarmor, that the author of 3d_armor wanted to add back, they wouldn't be able to, due to license incompatability. (But this applies to any mod we reuse, that's just an example.)
An example of this was seen for a long time with freeminer and Minetest, as MT wasn't able to use any changes made in freeminer, due to them switching to GPL.

**Comment by NewbProgrammer101** [comment]
OK, after further research, the poems were not actually licensed under CC BY-SA 3.0, I misunderstood in a Wikipedia article about LOTR and tolkiengateway.net list of poems, the CC license--where I misunderstood--actually only applied to user-contributed content, not the poems. 

Stupid me. 

I'm very, very glad you didn't merge these Tolkien-Estate-Copyrighted poems.

Rude comment warning:
5...
4...
3...
2...
1...
0...

Why on earth would you develop a subgame based on copyrighted content?

**Comment by NewbProgrammer101** [comment]
PS

I'm scrambling for starting work on my version of the poems.

**Comment by fishyWET** [comment]
> Why on earth would you develop a subgame based on copyrighted content?

It's the same reason why fanworks exists.

**Comment by Anth0rx** [comment]
> that the author of 3d_armor wanted to add back, they wouldn't be able to, due to license incompatability.

Okay, now it's clear

> To change the subject completely, here's the first bit of the rewrite which I mentioned to you a while ago: https://github.com/minetest-LOTR/Lord-of-the-Test/tree/v2-rewrite

Yes, I saw it already. I will try it out soon :)

**Pull request closed without merging**
