### PR TITLE
Replace some footstep sounds

### PR DESCRIPTION
**Pull request by Anth0rx**
So, I replaced some of the default footstep sounds. They will definitely need some remastering, but I wanted to know what is your opinion on these sounds.

### CODE REVIEW

**Comment by Anth0rx** [comment]
The previous commits were included by mistake.

**Comment by Anth0rx** [comment]
@Amaz1 What do you think of this?

**Comment by Anth0rx** [comment]
@Amaz1 Reminder :P

**Comment by Amaz1** [comment]
Sorry for my very late reply... I hope you'll excuse me for taking so long to get around to having a look at this!
I really like the new sounds, the only problem with them seems to be that they're a lot quiter than most of the current sounds, which is a little bit problematic. I don't know if you'd be able to increase their volume a bit?
Also, I'm not sure if this applies to footstep sounds: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L707 If it does, could you make the sounds mono please?

I don't know if I'll merge this into the current master branch of LOTT, it will probably go straight into the [v2-rewrite](https://github.com/minetest-LOTR/Lord-of-the-Test/tree/v2-rewrite) branch.

Thank you very much, and again, sorry for the very slow and late response.

**Comment by Anth0rx** [comment]
Hey, sure I will have a look at the volume levels and see if it is mono.

**Comment by Anth0rx** [comment]
So I thought it would be best if I amplified all sounds to the same level (I maxed them out without clipping). Now you can set the volume inside the code since they are all quite loud now in game.

**Pull request merged**
