### PR TITLE
race_texts.lua: Improve wording

### PR DESCRIPTION
**Pull request by FinishedFragment**
Fixes typos, improves grammar and wording.

Nothing major. There is still potential for more rewording since some of the sentences are very long for example.

### CODE REVIEW

**Comment by lumidify** [comment]
Hi,
Thanks for taking the time to proofread all the text.

I do have a few comments, though:
* On line 25, I'm pretty sure it was originally supposed to say "they awoke the balrog", which sounds better, in my opinion, than the alternative of "awakening the balrog" (ignoring, for the moment, that the replacement also has an extraneous "the" at the beginning).
* On line 64, I think "hidden potential, when events force them" shouldn't include a comma. I may be mistaken, though.
* On lines 101 and 106, I think the "a" should be kept. The phrase "a people" is used sometimes, especially together with a description such as "a very warlike people". In my opinion, it sounds better to keep it the way it is.

Do take everything I say here with a grain of salt - I'm not an English Major.

**Comment by FinishedFragment** [comment]
The problem is that I am also not an english major and I am not even a native english speaker, but I would argue I am a pretty fluent speaker.

Please do comment in the file, I think this is called reviewing, github has support for this. It would make the discussion a bit easier, too.

Regarding line 25, yes I see. I even omitted an "of".

I am not sure about line 64. I would say yes, but commas are always a difficult matter.

To be honest, I never heard "a people" before so this is why I regarded this as a typo. I would still change this though.

**Comment by lumidify** [comment]
I'll try to remember to use the review feature next time.

I still think "a people" sounds better in this context, but as I mentioned, I'm not the best person to ask. I'd rather wait for @Amaz1 to give his opinion on the matter, but that might take a while because he currently is busy with other things.

**Comment by Amaz1** [comment]
Line 64 - I think that a comma can be used or not - it just results in a slight change in emphasis. But, even though I'm a native speaker, my English grammar is not the best, so there could be a way that's more proper. Personally, I prefer it with a comma here.

Lines 101 and 106 - It should be "a people" here. People can be used as a synonym for nation, race, etc., if it's preceded by the definite or indefinite article, eg., the people of gondor, a large people, a people of high stature. It's a little bit old fashioned, but that was the intention here.

**Comment by BadToad2000** [comment]
Line 25, "they awoke the Balrog" is technically incorrect. While "woke" can be either transitive or intransitive, while "awoke" is always intransitive. Valid alternatives:
  a) "they woke the Balrog",   [transitive]
  b) "the Balrog awoke",         [intransitive]
  c) "the Balrog woke",           [intransitive]
  d) "the awakening of the Balrog" (contains no verbs)

If you choose "d", the line reads better as:
   "the awakening of the Balrog forced them out"

Line 106, "a people" is fine when talking about a group. Oddly "horse people" makes me think of centaurs, though I know what is meant, as will anyone else playing. Is there any reason the Rohan entry is almost entirely past tense?

A lore question, line 107 indicates that Rohan is named after the Rohirrim, but later text indicates Rohirrim is a name used outsider, and they call themselves Eorlingas. This seems to indicated the Rohan is the place name and Rohirrim was the name given to the people who live there. Maybe we should just get rid of **", named after them"**. It seems the text wants to say they are "a horse people who settled the land of Rohan". Yes, I see this comes from http://tolkiengateway.net/wiki/Rohirrim, and might actually come from some of Tolkien's works, but it bothers me. I think everyone can see the Rohan and Rohirrim are related, lets not say which comes from which.

**Comment by Amaz1** [comment]
> Line 25, "they awoke the Balrog" is technically incorrect. While "woke" can be either transitive or intransitive, while "awoke" is always intransitive. Valid alternatives:

Are you sure about this? In all the dictionaries I've consulted (Cambridge, Oxford, Collins.), it is given as a transitive and intransitive verb. e.g. https://www.oxfordlearnersdictionaries.com/definition/english/awake_2 However, I could quite possibly be confused over this :)

> Line 106, "a people" is fine when talking about a group. Oddly "horse people" makes me think of centaurs, though I know what is meant, as will anyone else playing. Is there any reason the Rohan entry is almost entirely past tense?

Yes, if it's taken out of context, it could be mistaken for centaurs! But with the context, it's clear, as you say. No, there's no particular reason, probably just not corrected when I was adapting it from Tolkien Gateway... It might be good to go through all of the entries and standardize them in the present tense, although there are also the historical descriptions as well... But maybe after this pull has been merged.

> A lore question, line 107 indicates that Rohan is named after the Rohirrim, but later text indicates Rohirrim is a name used outsider, and they call themselves Eorlingas. This seems to indicated the Rohan is the place name and Rohirrim was the name given to the people who live there. Maybe we should just get rid of **", named after them"**. It seems the text wants to say they are "a horse people who settled the land of Rohan". Yes, I see this comes from http://tolkiengateway.net/wiki/Rohirrim, and might actually come from some of Tolkien's works, but it bothers me. I think everyone can see the Rohan and Rohirrim are related, lets not say which comes from which.

Yep, I think getting rid of that bit is the best option.

Thank you for your help with this!

**Comment by Amaz1** [comment]
I've fixed the last couple of bits here.
Thank you very much!

**Pull request merged**
